# Generated by Django 4.1.1 on 2022-10-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quesmodel",
            name="ans",
        ),
    ]
