# Generated by Django 4.1.1 on 2022-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_quesmodel_ans"),
    ]

    operations = [
        migrations.AddField(
            model_name="quesmodel",
            name="ans",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
